### ISSUE TITLE
when enabled cursorline, my cursor is invisible

### ISSUE THREAD

**Issue by ttys3** [shaunsingh/nord.nvim#24] opened 2021-07-20 17:06 UTC
when enabled cursorline, my mouse is invisible

this is visible because I have rainbow plugin enabled, it colored the `{`
![image](https://user-images.githubusercontent.com/41882455/126365921-fc58a8ab-65a4-42ed-948b-97b2338c107a.png)

the cursor is invisible (the cursor actually at column 1):

![image](https://user-images.githubusercontent.com/41882455/126365991-44a5009f-833a-401d-a789-777133d272fa.png)

**Comment by ttys3** [comment] 2021-07-20 17:11
and it also does not play well with `rrethy/vim-illuminate` plugin

![image](https://user-images.githubusercontent.com/41882455/126366710-6a591dd1-1621-40fd-8ee1-9e80c6efaf2b.png)

**Comment by shaunsingh** [comment] 2021-07-20 17:13
> the cursor is invisible (the cursor actually at column 1):

I use nord4 for the cursor and nord1 for the cursor line, so it shouldn't be an issue, I'll take a look and see if I can replicate it though 

> and it also does not play well with rrethy/vim-illuminate plugin

Thanks, I'll fix that right away

**Comment by shaunsingh** [comment] 2021-07-20 17:19
Second issue should be fixed now
this:https://github.com/shaunsingh/nord.nvim/commit/994cb6b4efa481ac1a64aa3ac5c9e8cfea806783

**Comment by shaunsingh** [comment] 2021-07-20 17:23
> when enabled cursorline, my mouse is invisible

I can't reproduce this on neovide, xterm.js (vscode terminal), or Alacritty. What terminal emulator are you using, and do you have your dot files somewhere so I can take a look?

<img width="852" alt="image" src="https://user-images.githubusercontent.com/71196912/126368362-e87fc856-d5d1-494a-b930-161875ae59dd.png">

**Comment by ttys3** [comment] 2021-07-23 01:03
> > when enabled cursorline, my mouse is invisible
> 
> I can't reproduce this on neovide, xterm.js (vscode terminal), or Alacritty. What terminal emulator are you using, and do you have your dot files somewhere so I can take a look?
> 
> <img alt="image" width="852" src="https://user-images.githubusercontent.com/71196912/126368362-e87fc856-d5d1-494a-b930-161875ae59dd.png">

you can not move the cursor under a `char`, try the blank line

**Comment by shaunsingh** [comment] 2021-07-23 01:35
I assume you're using Alacritty (or some terminal emulator that uses this effect). Alacritty actually takes the foreground color, and uses it as the cursor color. Unless you disable either 
1. the effect for all of Alacritty or 
2. the cursor line effect
I can't help you from my end. This isn't something neovim can control, sorry

**Comment by ttys3** [comment] 2021-07-23 15:02
yes, I'm a Alacritty user.

no, when I use gruvbox.nvim under Alacritty.
the cursor is OK

![image](https://user-images.githubusercontent.com/41882455/126801205-fa447cac-d0b7-49c0-b60e-8bce20714916.png)

![image](https://user-images.githubusercontent.com/41882455/126801392-897b67a8-8e84-4969-a9f5-559e878efe9e.png)

**Comment by shaunsingh** [comment] 2021-07-23 15:21
> no, when I use gruvbox.nvim under Alacritty.

Thats because the cursor line color for gruvbox is different from the one used for the cursor line, while I (according to the nord docs) should use the same color for both. 

Regardless, could you kindly try the original Nord-vim theme and see its behavior? I try to be somewhat accurate to the original vim implementation, so if the issue doesn't occur with the original theme I'll if I should change the colors

**Comment by shaunsingh** [comment] 2021-07-23 15:54
If you want to use proper multithreaded lua, I recommend you view this video: https://www.youtube.com/watch?v=GToxQKi7LZg&feature=youtu.be

Plenary.nvim is the only one (currently) that can handle such events through a wrapper on libluv. I'm not sure how you expect the same results when the operation is clearly single threaded

**Comment by ttys3** [comment] 2021-07-23 15:56
@shaunsingh  the original theme is OK

![image](https://user-images.githubusercontent.com/41882455/126809012-3cb3e104-a63f-4bbe-bbbe-2c899c3db4cc.png)

**Comment by shaunsingh** [comment] 2021-07-23 15:58
Ah, Thanks for pointing that out then. I'll fix the theme and update it

**Comment by shaunsingh** [comment] 2021-09-08 18:31
Should be fixed now, lmk if you have any other issues

**Closed by shaunsingh** 2021-09-08 18:31 UTC
